"""empty message

Revision ID: 43954ad4ccc2
Revises: be4b75e8b211
Create Date: 2020-12-22 22:03:10.326397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43954ad4ccc2'
down_revision = 'be4b75e8b211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['name'])
    op.create_unique_constraint(None, 'venues', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
