"""empty message

Revision ID: 629293bfd0f5
Revises: 43954ad4ccc2
Create Date: 2020-12-23 22:40:00.451577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629293bfd0f5'
down_revision = '43954ad4ccc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_name_key', 'artists', type_='unique')
    op.drop_constraint('venues_name_key', 'venues', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venues_name_key', 'venues', ['name'])
    op.create_unique_constraint('artists_name_key', 'artists', ['name'])
    # ### end Alembic commands ###
